### ISSUE TITLE
Had to copy XIB resource into my project

### ISSUE THREAD

**Issue by kylestew** [autresphere/ASMediaFocusManager#25]
There seems to be an issue where CocoaPods (or something else) isn't installing the needed XIB resource into the final binary. It doesn't crash the app, but nothing loads. The screen is only darkened, no images are displayed. This was from a fresh install from CocoaPods.

**Comment by autresphere** [comment]
Just tried a fresh install with cocoa pods on a new project, no issue on my side.
Can you try again and maybe send me a simple project with the issue?
