### ISSUE TITLE
FullScreen not covering NavigationBar and TabBar

### ISSUE THREAD

**Issue by boazin** [autresphere/ASMediaFocusManager#27]
I'm probably doing something wrong, but I did almost exactly like the example code - but still the fullscreen doesn't hide the navigation bar on top and the UITabBar on bottom. Is it because the original view controller on the storyboard has "Under Top Bars" and "Under Bottom Bars"? If so, what can be done?

Thanks
(awesome project...)

**Comment by boazin** [comment]
Well, I managed to make it cover the navigationbar:
```
- (CGRect)mediaFocusManager:(ASMediaFocusManager *)mediaFocusManager finalFrameForView:(UIView *)view
{
    return [[UIScreen mainScreen] bounds];
}

- (UIViewController *)parentViewControllerForMediaFocusManager:(ASMediaFocusManager *)mediaFocusManager
{
    return self.navigationController;
}
```

Still have a problem with the UITabBar (the overlay is not on top it)

Any ideas?

**Comment by autresphere** [comment]
Have you tried to return a parent view controller that contains your UITabBar and that is not a UITabBarController. For example if you use a UITabBarController, you should return the UITabBarController's parentViewController.

**Comment by chavira** [comment]
Taking part from @boazin and other from @autresphere for UITabBar: 

- (CGRect)mediaFocusManager:(ASMediaFocusManager *)mediaFocusManager finalFrameForView:(UIView *)view
{
    return [[UIScreen mainScreen] bounds];
}

- (UIViewController *)parentViewControllerForMediaFocusManager:(ASMediaFocusManager *)mediaFocusManager
{
    return self.tabBarController.parentViewController;
}

**Comment by jwardle** [comment]
The following, in Swift, worked for me: It now covers the full screen - TabBar and NavBar

    func parentViewControllerForMediaFocusManager(mediaFocusManager: ASMediaFocusManager!) -> UIViewController! {
        return UIApplication.sharedApplication().delegate!.window!!.rootViewController;
    }
