### ISSUE TITLE
No keyboard handling can lead to cases where keyboard overlays focusViewController

### ISSUE THREAD

**Issue by oseparovic** [autresphere/ASMediaFocusManager#32]
I'm not sure if there's currently a way to work around this but if you ever trigger a focus gesture on an image while the keyboard is up, the keyboard will remain active and will overlap the focusViewController.

A quick fix I did was simply to add the following:

```
- (void)handleFocusGesture:(UIGestureRecognizer *)gesture
{
    // ...
    [parentViewController.view endEditing:YES];
    // ...
}
```

I'm not sure this is the best contribution to the lib though as this *might* lead to unexpected behaviour on the user's end. Perhaps a `BOOL` property to hide the keyboard when focusing might better? Thoughts?

**Comment by autresphere** [comment]
As you're saying, this might lead to unexpected behavior. I think you'd better dismiss your keyboard in one of the delegate's method, for example inside ```[ASMediasFocusDelegate parentViewControllerForMediaFocusManager:]```.

**Comment by oseparovic** [comment]
That sounds pretty reasonable. Thanks!
