### ISSUE TITLE
Question: Can i close the fullscreen from the outside?

### ISSUE THREAD

**Issue by robertodias180** [autresphere/ASMediaFocusManager#34]
I want to close the view if X condition are True. Is there a way to close it from the outside?

Thanks  

ps:  I made a function for that. If there is one already that does it please let me know.

**Comment by autresphere** [comment]
No there is no way to close a focused view programmatically. Pul Request is more than welcome!

**Comment by robertodias180** [comment]
Working on it. Will send a pull request went it is working.

**Comment by robertodias180** [comment]
Pull sent :D check it when you have time.

**Comment by autresphere** [comment]
Done, thanks for the PR!
