### ISSUE TITLE
endFocusing

### ISSUE THREAD

**Issue by chavira** [autresphere/ASMediaFocusManager#40]
As is mentioned in the main page:

"If you need to focus or defocus a view programmatically, you can call startFocusingView ()as long as the view is focusable) or endFocusing."

I cannot find the 'endFocusing' method or something similar to close the focusing image.

Do I miss something?

**Comment by autresphere** [comment]
This wasn't part of the 0.3 release.
A new release has been pushed, you should now have access to it if you update your pod.
