### ISSUE TITLE
Load a UIImage?

### ISSUE THREAD

**Issue by nnhubbard** [autresphere/ASMediaFocusManager#45]
Is it possible to load just a `UIImage` object rather than having to reference an image from URL?

**Comment by autresphere** [comment]
If you already have your full size image, then you can use [ASMediasFocusDelegate mediaFocusManager:cachedImageForView:] to pass it to the focus manager.
But you still need to return a non nil URL in [ASMediasFocusDelegate mediaFocusManager:mediaURLForView:] or else the cachedImageForView method won't be called (this is an issue that has to be fixed, PR welcome). This URL can be anything even if it does not point to an actual image (it can even be a broken link as it is not actually used).

**Comment by nnhubbard** [comment]
Thanks. Got it working.
