### ISSUE TITLE
How to customise buttons

### ISSUE THREAD

**Issue by Edig** [autresphere/ASMediaFocusManager#49]
I implement ASMediaFocusManager in my project but, I don't know how to customise the button, I need a delete and a flash button plus the done button.

is there a way to do this?

**Comment by autresphere** [comment]
Which button from ASMediaFocusManager do you want to customize?

**Comment by Edig** [comment]
The "Done" button with my own custom design and add a new button in the right button part

**Comment by TiagoVeloso** [comment]
I would also like this feature

**Comment by autresphere** [comment]
Now you can specify your own UIViewController by using the new property topAccessoryController.
