### ISSUE TITLE
Cant play videos

### ISSUE THREAD

**Issue by Edig** [autresphere/ASMediaFocusManager#50]
Hi,

I implement MediaFocus and Player and I get this error

```*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICustomObject 0x1742043d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key currentTimeLabel.'````

**Comment by autresphere** [comment]
Hi Eduardo,

MediaFocus uses another library called ASBPlayerScrubbing which should be automatically included if you use cocoapods. Can you check this is included in your project? You can also look into the classes and ressources, you will see ASVideoControlView.xib which has a label linked to the currentTimeLabel outlet of an inner PlayerScrubbing object. Can you check everything is correct here?
There should not be any problem unless you did some changes in this xib by mistake.

**Comment by Edig** [comment]
Actually I manually add to my pods "ASBPlayerScrubbing" and still the same, I didn't modify the XIB files before that error, after that I try several things and didn't work.  BTW, my project is in SWIFT, maybe this is the problem. I have encounter allot of troubles when implementing obj-c in swift.

I add "ASBPlayerScrubbing" in my bridge file

**Comment by autresphere** [comment]
I don't know of any issue related to Swift. Maybe you could try on a small Obj-C project to check everything is ok on your side?

**Comment by Edig** [comment]
Ley my try and I will tell you

**Comment by autresphere** [comment]
Any news?

**Comment by autresphere** [comment]
No news, so I'm closing it.
