### ISSUE TITLE
Use this in swift??

### ISSUE THREAD

**Issue by soyoh** [autresphere/ASMediaFocusManager#53]
Hello,
i'm new in iOS development, and i'd like to use this pod in one project, do you have any example or quick guide how to use it with swift??
Thanks.

**Comment by naru** [comment]
After installing through cocoapods

in your **Bridging-Header.h**
```swift
#import "ASMediaFocusManager.h"
```

inYourViewController.swift
```swift
import ASMediaFocusManager

class YourViewController: UIViewController {

  override func viewDidLoad() {
      super.viewDidLoad()
      let mediaFocusManager = ASMediaFocusManager()
  }
...

}
```
