### ISSUE TITLE
Image not changing orientation when the device orientation changed

### ISSUE THREAD

**Issue by tkohout** [autresphere/ASMediaFocusManager#55]
Hi,
thanks for this awesome component. It makes a lot of stuff easier. But there is still some issues:

This is only happening when I have UIViewController inside NavigationController and the supportedInterfaceOrientations is set to UIInterfaceOrientationMaskPortrait 

I am testing on iOS 8.3 right now

```
- (NSUInteger)supportedInterfaceOrientations
{
    return UIInterfaceOrientationMaskPortrait;
}
```

The parentViewController is set to self.navigationController

Now when I enlarge the image and change the orientation nothing happens. Although if I would set parentViewController = self it would work.

I dug into code and found out why it is not working:

in ASMediaFocusController in viewDidAppear
the controller subscribes to receive Orientation change notification. When is the parentViewController a navigationController it is simply not being called. I am not sure why it is when in the other case it works perfectly fine.

**Comment by razvan-paul** [comment]
+1

**Comment by razvan-paul** [comment]
Did you find any solution?

**Comment by razvan-paul** [comment]
UPDATE

If anyone interested, I sorted it out using this:

https://github.com/mobileplayer/mobileplayer-ios/issues/142
