### ISSUE TITLE
I can't make it work with Swift

### ISSUE THREAD

**Issue by itleo31** [autresphere/ASMediaFocusManager#59]
Hello team,

First of all, thank you for incredible works. I'm trying to apply your lib to my project but I'm getting stuck and cannot make this work. I'm using Swift and Cocoapods.

Enclosed is the project. I would be very appriciate if you can help me take a look at my code and let me know what I was missing.

Thanks & Best Regards
Khanh pham
[Test.zip](https://github.com/autresphere/ASMediaFocusManager/files/74712/Test.zip)

**Comment by mkc842** [comment]
Any progress with this? I am encountering the same. Thanks

**Comment by itleo31** [comment]
This can be fixed by adding Bundle to your project.
