### ISSUE TITLE
enforce UIImageView type for installOnView, or extend functionality to any UIView

### ISSUE THREAD

**Issue by mkc842** [autresphere/ASMediaFocusManager#60]
The install method is called installOnView, and it allows you install to a view that is not a UIImageView. This is misleading, since things don't actually work unless you install to a UIImageView. Perhaps the method should be called installOnImageView and should throw an error if the type is wrong? Or better yet, enable this to work with any UIView. Cool library, thank you.

**Comment by autresphere** [comment]
If you call installOnView on a view which is not a UIImageView, then you must supply a UIImageView through the @optional delegate method [mediaFocusManager: imageViewForView:].
Does it make sense to you?
