### ISSUE TITLE
MediaFocusManager focused -> Press Home Button -> Open app from background -> App Freezed

### ISSUE THREAD

**Issue by gathan** [autresphere/ASMediaFocusManager#68]
Hi,

In this usecase

User taps a photo -> MediaFocusManager focused -> Press Home Button -> Open app from background -> App Freezed

A freezing happens (ASTransparentView is on top of everything).

Is it an ASMediaFocusManager or a bad implementation?

**Comment by dogo** [comment]
Hi, @gathan 

Probably a bad implementation, I tested here with the sample app and another app and everything runs fine.

iPhone 6 16GB
iOS 9.3.2 (13F69)

**Comment by autresphere** [comment]
Thanks for your feedback @dogo!
